on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [bootstrap.sh]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir out
          cp bootstrap.sh out/index.html
      - uses: actions/upload-pages-artifact@v5
        with:
          path: out
      - uses: actions/deploy-pages@v5
        id: deployment
